### ISSUE TITLE
When validation fails, provide a reason to the caller

### ISSUE THREAD

**Issue by bobharner** [RohanNagar/jmail#101]
[An enhancement, not a bug]

Whenever an email fails to pass validation, no information is provided to the caller about what the problem was.  Was there an invalid character in the domain?  Were there multiple "@" characters?  Was the "@" character missing?  Was there no ending domain (part after the last dot?).  Something else?

I recommend adding some way for the caller to get back a string that describes the problem.  These descriptions are mostly available in the code in the form of comments ("email cannot be more than 320 chars", "email cannot start with '.'", "email cannot end with '.' or '-'", etc.) but not available to the caller.  Ideally the descriptions would be understandable to a naive end user.

In comparison, https://github.com/lite2073/email-validator does a MUCH better job of providing a description of the exact cause of the problem, but that project is getting a bit stale.

**Comment by RohanNagar** [comment]
Hi @bobharner thanks for opening this issue! I think this is a good  and useful enhancement, I plan to prioritize adding this feature next.

**Comment by RohanNagar** [comment]
I finally have started work on this issue. There are a lot of places where validation can fail, so it is a bit involved 🙂

Essentially there will be a new method called `validate(String address)` that will return an `EmailValidationResult` object. This object will contain the result of the validation, the reason why it failed (if any), and the parsed `Email` object if successful.

I will update this issue once again once the change is complete.

**Comment by RohanNagar** [comment]
I just merged #124, which adds this feature. I plan on releasing a new version in the next week that will contain this change.

**Comment by RohanNagar** [comment]
Version 1.5.0 is released and now available on Maven Central. Please try it out and see if this meets your needs!
