### ISSUE TITLE
E-Mail Address Validation on https://www.rohannagar.com/jmail/ broken

### ISSUE THREAD

**Issue by PascalSchumacher** [RohanNagar/jmail#115]
E-Mail Address Validation on https://www.rohannagar.com/jmail/ seems broken, even `name@example.com` gives `The email address is invalid. `

**Comment by RohanNagar** [comment]
Thanks for opening this issue! You are correct that the website is broken. I have a backend API that was deployed on Heroku, and it appears that the Heroku free tier is now gone, so my server is down.

I will need to set up a new one on AWS or something similar. Will prioritize this work.

**Comment by PascalSchumacher** [comment]
Thank you very much! 👍

**Comment by RohanNagar** [comment]
@PascalSchumacher I have created a new backend for the JMail API on AWS, and updated the website. The online validation should be working again now.

Thank you for your patience!

**Comment by PascalSchumacher** [comment]
Thank you very much! 👍
