### ISSUE TITLE
Valid email shown as invalid

### ISSUE THREAD

**Issue by aloketewary** [RohanNagar/jmail#132]
**Is this bug report about an incorrectly validated email address?**

- [X] Yes
- [ ] No

**If yes, what is the email address?**

1234567890123456789012345678901234567890123456789012345678901234+x@example.com

- [X] Valid
- [ ] Invalid

**If no, please describe the bug**

**Additional context**

I found the list from here
https://docs.blackberry.com/en/id-comm-collab/blackberry-athoc/blackberry-athoc/7_9/create-publish-alerts/email-format-validation/valid-email-address-examples

**Comment by RohanNagar** [comment]
Thank you for reporting! It looks like this email is being marked as invalid since the local-part of the address (the part before the `@` symbol) is 66 characters long. 

The validation code checks to make sure the local part is not longer than 64 characters.

I am out of town at the moment but I will check into the RFCs to make sure that this character limit on the local part is correct.

**Comment by aloketewary** [comment]
Hello @RohanNagar,

I noticed that the email address `aloketewary@gmail` is being treated as valid. However, it appears to be incomplete. Could you please confirm if this is still considered a valid email address?

Thank you.

**Comment by RohanNagar** [comment]
@aloketewary just saw your second question. `aloketewary@gmail` is indeed a valid email address, although it is missing the top level domain.

You can see that all other libraries also consider this type of email address as valid:

<img width="1619" alt="Screen Shot 2023-03-20 at 11 24 22 AM" src="https://user-images.githubusercontent.com/5522930/226432307-1f37a13e-ea9f-4a10-95ef-28f5f759ffac.png">

JMail does recognize that you usually don't want these addresses to be considered valid, so it is recommended to use `JMail.strictValidator()` as your `EmailValidator`, which will correctly mark the given email address as invalid:

```java
// do this: returns false as you expect
boolean isValid = JMail.strictValidator().isValid("aloketewary@gmail");
```

**Comment by aloketewary** [comment]
Thank you for bringing the 64 character limit for the local part of the email address to my attention. I appreciate it.
Aah got it thanks man for your time. Closing this ticket.

**Comment by RohanNagar** [comment]
Sounds good!

Just FYI if you are using the online email validation tool, I plan on adding some additional features to that tool in the next month to allow you to consider those types of emails as invalid, as well as some other features, so stay tuned 🙂

**Comment by aloketewary** [comment]
Just add the failure message in response to that online tool as well. it will help alot in future.

**Comment by RohanNagar** [comment]
@aloketewary I have added the failure reason to the response on the website. Hope that helps!
