### ISSUE TITLE
Please either make EmailValidator immutable or support clone()

### ISSUE THREAD

**Issue by bbottema** [RohanNagar/jmail#14]
Hey Rohan,

In Simple Java Mail I started replacing the email library with JMail, but I noticed one principle that Simple Java Mail relies on that is not possible with JMail: the guarantee that once a value is passed in, it cannot change after that. And as a general principle, I think this important to have in any software design. To support my point I would like to remind you that many code checkers like Spotbugs (FindBugs)/Sonar etc. also complain if you just pass in say an array that can be mutated outside of the method it is passed in.

Would you please make `EmailValidator` either _immutable_ (the fluent/builder api returns a new instance on each call) or supporting `clone()` so I can clone it in my own api?

**Comment by RohanNagar** [comment]
Thanks for opening this! Definitely in favor of making it immutable. I just released v1.2.1 (containing 20085c5) that fixes this (should be available in central in about 10 minutes).
