### ISSUE TITLE
Make timeout configurable for DNS MX record lookup

### ISSUE THREAD

**Issue by dotneutron** [RohanNagar/jmail#152]
There are 2 obscure extra properties that control the initial timeout and retries in JNDI.
* `com.sun.jndi.dns.timeout.initial` - the default is `1000` (ms)
* `com.sun.jndi.dns.timeout.retries` - the default is `4`

These go in the `env` Hashtable passed to `InitialDirContext`.

Currently, checking if an MX record exists for a domain like `coolio.com` is super bad for performance. Since user input cannot be trusted, perhaps this could be configurable.

Awesome lib, btw. 💯

**Comment by RohanNagar** [comment]
Hi @dotneutron, thank you for opening this issue and bringing this to my attention, I didn't know that these configuration options existed!

I'm actually now considering setting a lower default within JMail, along with allowing for configurable timeout and retries. Maybe a default of 100ms for the initial timeout and 2 retries.

What do you think?

**Comment by RohanNagar** [comment]
I went ahead and made these changes and released version 1.5.1 which contains the new feature. Thanks again for the suggestions!
