### ISSUE TITLE
Add changelog file

### ISSUE THREAD

**Issue by goodale** [RohanNagar/jmail#176]
Is there a changelog available?   I'm not seeing a 'Wiki' page or other changelog page on the jmail github project or jmail site.

**Comment by RohanNagar** [comment]
Hi @goodale, thanks for opening this issue.

The [releases page](https://github.com/RohanNagar/jmail/releases) details all of the changes included in each release.

It would probably be a good idea to add a CHANGELOG.md file to the repo too. I'll keep this issue open until that is done.

**Comment by goodale** [comment]
thank you!

**Comment by RohanNagar** [comment]
[CHANGELOG.md](https://github.com/RohanNagar/jmail/blob/master/CHANGELOG.md) has been added to `master`.

Thanks again for opening this issue!
