### ISSUE TITLE
Does not work for email Ids containing spaces

### ISSUE THREAD

**Issue by rahul-k-srvastva** [RohanNagar/jmail#178]
**Is this bug report about an incorrectly validated email address?**

- [*] Yes
- [ ] No

**If yes, what is the email address?**
das-01 @ rediffmail.com

- [ ] Valid
- [*] Invalid

**Comment by RohanNagar** [comment]
Hi @rahul-k-srvastva, thank you for opening this issue!

This email is in fact valid according to RFC. Whitespace is allowed between dot-separated parts of the address, and the `@` (at) symbol acts as a dot-separator.

However, this often isn't desired. You can treat these addresses as invalid by adding the `disallowObsoleteWhitespace()` rule to your validator. For example:

```java
  @Test
  void test() {
    String email = "das-01 @ rediffmail.com";

    // The default validation allows this address
    assertThat(JMail.isValid(email)).isTrue();

    // Use disallowObsoleteWhitespace to make the validator reject the address
    assertThat(JMail.validator().disallowObsoleteWhitespace().isValid(email)).isFalse();
  }
```

Hope that helps! Thanks again for opening this issue!
