### ISSUE TITLE
Failure Reason incorrect

### ISSUE THREAD

**Issue by tbatchlear** [RohanNagar/jmail#183]
**Is this bug report about an incorrectly validated email address?**

- [X] Yes
- [ ] No

**If yes, what is the email address?**
email@example.com-

- [ ] Valid
- [X] Invalid

Reason given for failure is incorrect.  Reason should be `DOMAIN_PART_ENDS_WITH_DASH` but is `ENDS_WITH_DOT`.

**Comment by RohanNagar** [comment]
Thanks for reporting @tbatchlear! This is indeed a bug. The fix has been made and published in v1.6.1.
