### ISSUE TITLE
IPv4 validation allows non-standard digit characters

### ISSUE THREAD

**Issue by harrel56** [RohanNagar/jmail#189]
**Is this bug report about an incorrectly validated email address?**

- [ ] Yes
- [x] No

**If yes, what is the email address?**

- [ ] Valid
- [ ] Invalid

**If no, please describe the bug**
Let's consider something like:
```java
InternetProtocolAddress.validateIpv4("1২7.0.0.1");
```
and it validates successfully. Looks like java is more lenient when it comes to numbers than I thought: invoking `Integer.parseInt("1২7")` returns `127` ( `২` is `2` in Bengali).

I suppose this example should not be considered a valid ipv4 (actually it affects ipv6 too) address?

**Additional context**

**Comment by RohanNagar** [comment]
Version 1.6.2 is now released with the fix. Thanks again for reporting this bug @harrel56!

**Comment by harrel56** [comment]
Great, thanks for a quick fix!
