### ISSUE TITLE
Question: preceding zeros in IPv4 address

### ISSUE THREAD

**Issue by harrel56** [RohanNagar/jmail#190]
**Is this bug report about an incorrectly validated email address?**

- [ ] Yes
- [x] No

**If yes, what is the email address?**

- [ ] Valid
- [ ] Invalid

**If no, please describe the bug**
Should e.g. `0127.0.0.1` be considered a valid address? Or even `0000000127.0.0.1`? Now it validates correctly - what do you think?

**Additional context**

**Comment by RohanNagar** [comment]
Thanks for this report as well @harrel56. Agree that those addresses should not be valid, will work on a fix for this.

**Comment by RohanNagar** [comment]
Version 1.6.2 is now released with the fix. Thanks again for reporting this bug @harrel56!

**Comment by harrel56** [comment]
@RohanNagar Hmm, what about cases where IP part has correct length but still starts witch zeros? Like `001.0.0.1` or `088.088.088.088`? Can be these considered valid?

**Comment by harrel56** [comment]
Yeah, I don't really have knowledge in this area so it's fine - just wanted to ensure it was intended :)
