### ISSUE TITLE
Support no service resource record for domains that accept no mail "Null MX"

### ISSUE THREAD

**Issue by elmolm** [RohanNagar/jmail#191]
**Please describe the feature that you are requesting**
Emails with a no service resource MX record (https://datatracker.ietf.org/doc/html/rfc7505) should be validated as false. for example test@gmail.de

**Comment by RohanNagar** [comment]
@elmolm thank you very much for raising this improvement and also opening a PR for the feature! 🙏 The PR has been merged and I will release a new update within the next week or so.

Leaving this open until the release is done.

**Comment by RohanNagar** [comment]
Version 1.6.2 is now released with your improvement. Thanks again for your contributions @elmolm, it is very appreciated!
