### ISSUE TITLE
Feature request: some sort of email normalization?

### ISSUE THREAD

**Issue by psimonazzi** [RohanNagar/jmail#50]
Given the quite loose definition of the email standard forms, it could be useful to provide some sort of normalization of the Email object, to render it in a way that most people commonly recognize as a plain and bare email address.
That would be equivalent to stripping comments, optional parts, etc.: 
`email.localPartWithoutComments() + "@" + email.domainWithoutComments()`.
This feature could be useful for example when we not only want to validate the address as a mail recipient, but use it as some sort of identifier (for example in login systems).

**Comment by RohanNagar** [comment]
Hi @psimonazzi, thank you for your comment. Am I correct in my understanding that you are asking for a new convenience method on the `Email` object that returns the email address with solely the local-part and the domain, without any comments or identifiers?

That should be straightforward to add as it would be the same as doing `email.localPartWithoutComments() + "@" + email.domainWithoutComments()`, but I want to make sure that is what you are asking for.

**Comment by psimonazzi** [comment]
Hi, yes, I think that would do, thanks.

**Comment by RohanNagar** [comment]
Thanks! I have merged the improvement and released version v1.4.0 which contains the new method.
