### ISSUE TITLE
Addressess with explicit source routing are not valid

### ISSUE THREAD

**Issue by XakepSDK** [RohanNagar/jmail#6]
**Is this bug report about an incorrectly validated email address?**

- [x] Yes
- [ ] No

**If yes, what is the email address?**

`@1st.relay,@2nd.relay:user@final.domain`

- [x] Valid
- [ ] Invalid

**If no, please describe the bug**

Address syntax
https://datatracker.ietf.org/doc/html/rfc822#section-6.1
Example of such address with explicit routes
https://datatracker.ietf.org/doc/html/rfc1711#section-7

**Additional context**

Not sure if this was superseded by newer RFCs

**Comment by RohanNagar** [comment]
Thank you for the detailed report @XakepSDK!

This is definitely an interesting case, I'll take some time to dig into source routing. Right now it looks like I'll want to support it, but I want to make sure it is still considered valid.

**Comment by RohanNagar** [comment]
I fixed this with c23a3c9.

I decided that since it technically is still valid according to RFC, it should be allowed by default. However, `JMail.strictValidator()` will not allow for explicit source routing and in production it should not be allowed either.
