### ISSUE TITLE
Incorrect email

### ISSUE THREAD

**Issue by Okenlyzavals** [RohanNagar/jmail#64]
**Is this bug report about an incorrectly validated email address?**

- [x] Yes
- [ ] No

**If yes, what is the email address?**
mymont@noыыыы

- [ ] Valid
- [x] Invalid

**If no, please describe the bug**

**Additional context**

**Comment by RohanNagar** [comment]
Hi @Okenlyzavals,

Thank you for the report!

This email address is in fact valid by default if you are using `JMail.isValid()`, as the RFC does allow for a local domain name with no TLD.

It is recommended to use `JMail.strictValidator()` as your `EmailValidator`, which will correctly mark the given email address as invalid:

```java
// do this: returns false as you expect
boolean isValid = JMail.strictValidator().isValid("mymont@noыыыы");
```
