### ISSUE TITLE
Add documentation for all default validation rules

### ISSUE THREAD

**Issue by scott-abernethy66** [RohanNagar/jmail#91]
This library is great! I would very much like to use it in a project I'm working on but I can't find any documentation that spells out each of the validation rules that it enforces.  Do you have a list somewhere that I just missed?

**Comment by RohanNagar** [comment]
Hi @scott-abernethy66, thanks for your interest!

You're right that there is currently no list that spells out each validation rule that is enforced. It follows the RFC for email addresses when doing validation, but those are not very easy to parse through 🙂 

I think it would be a good idea to list out the things that are always enforced when doing basic validation. I do already have a [list of additional validation rules](https://jenkins.pod.box.net/blue/organizations/jenkins/Infra%2FDocker-Shell/detail/Docker-Shell/5929/pipeline) that can be applied.

I am currently out of town traveling for a few weeks but I will try to get to this as soon as I get back!

**Comment by RohanNagar** [comment]
Hi @scott-abernethy66, thank you for your patience on this issue.

I just recently merged #124, which is a feature addition to the library that provides details on why certain email addresses failed validation. As part of that, there is now an enum that enumerates many of the various validation rules that are enforced based on the RFCs: https://github.com/RohanNagar/jmail/blob/master/src/main/java/com/sanctionco/jmail/FailureReason.java

Each reason is documented with JavaDocs to explain it in a bit more detail. Do you think this documentation is what you were looking for?

**Comment by RohanNagar** [comment]
@scott-abernethy66 please see https://javadoc.io/doc/com.sanctionco.jmail/jmail/latest/com.sanctionco.jmail/com/sanctionco/jmail/FailureReason.html for the description of what I mentioned in my previous comment.

I am going to consider this done for now, but if you need something more please feel free to reopen the issue.
